import type { Metadata } from 'next'
import '../styles/globals.css'
import Toast from '@/components/common/toast/Toast'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css"
        />
        <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
      </head>
      <body className={`font-pre`} suppressHydrationWarning>
        <Toast />
        {children}
      </body>
    </html>
  )
}
